language: objective-c
osx_image: xcode8
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project SPTinderView.xcodeproj -scheme SPTinderView -destination 'platform=iOS Simulator,name=iPhone 7' build | xcpretty;
  - echo "3.1" > .swift-version
  - pod lib lint;

branches:
  only:
    - master